### ISSUE TITLE
[BUG] Deleting Virtual Space Zone items causes crash

### ISSUE THREAD

**Issue by ExpiredPopsicle** [Inochi2D/inochi-session#29] opened 2023-04-23 16:57 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Due to a threading issue the threads for virtual space zone items are not appropriately cleared. This causes the garbage collector to attempt to delete stale memory.

### Reproduction

See description.

### System Architecture

None

### Operating System

None

**Comment by LunaTheFoxgirl** [comment] 2023-05-01 11:45
This may have been fixed by https://github.com/Inochi2D/inochi-session/commit/aaaa22166e18cee5fc1355ef1b1a3c2de337f857, I can't reproduce this crash anymore.

**Closed by LunaTheFoxgirl** 2023-05-01 11:45 UTC
Labels: Bug
