### ISSUE TITLE
Error: No valid OpenGL 4.2 context was found!

### ISSUE THREAD

**Issue by EzequielBruni** [Inochi2D/inochi-session#8] opened 2022-08-10 06:59 UTC
Hey there. I gave the latest release build a quick test, and ran into the following error:

```
./inochi-session-x86_64.AppImage
[INFO] Inochi Session v0.5.4, args=[]
[INFO] Lua support initialized. (Statically linked for now)
[INFO] Scanning plugins at /home/ezequiel/.config/inochi-session/plugins...
object.Exception@inui/source/inui/core/window/appwin.d(235): No valid OpenGL 4.2 context was found!
----------------
??:? [0x558e2abc8096]
??:? [0x558e2abc9ba6]
??:? [0x558e2abab1af]
??:? [0x558e2aab35ea]
??:? [0x558e2aa4cfa5]
??:? [0x558e2aa633f9]
??:? [0x558e2abaae9b]
??:? [0x558e2abaad95]
??:? [0x558e2abaabed]
??:? [0x7f4d21a3554f]
??:? __libc_start_main [0x7f4d21a35608]
??:? [0x558e2aa491e9]
fish: Job 1, './inochi-session-x86_64.AppImage' terminated by signal SIGSEGV (Address boundary error)
```

Running the command in the bash shell (fish is my usual) adds this line to the end of the error message:

```
Segmentation fault (core dumped)
```

My system information:
* OS: Fedora 36
* Display server: X11
* Processor: i7-4790
* Graphics: Nvidia GTX1070 with proprietary drivers.

3D and OpenGL apps in general seem to work, so I really don't think the problem is with my system specifically. I should probably also mention that I get this error with the zipped version of the release as well.

**Comment by LunaTheFoxgirl** [comment] 2022-08-10 11:07
Current theory is that NVIDIA's support for EGL on X11 is somewhat broken. Am trying to confirm whether this is the case.

**Comment by EzequielBruni** [comment] 2022-08-11 02:29
Wouldn't be the first time Nvidia's Linux drivers up and bugged out, I suppose. I'll be interested to see what you find in the end.

**Comment by EzequielBruni** [comment] 2022-08-11 02:43
Update: It did work just fine on Wayland. Also, it worked fine on X11 in RegataOS, which is based on openSUSE leap 15.4. It could be some sort of bug in Fedora's versions of the libraries, perhaps. I'm going to look into this Nvidia/X/EGL thing and let you know if I find anything useful.

**Comment by grillo-delmal** [comment] 2022-08-11 13:56
I maintain a barebones build for Fedora in COPR, can you check if that build is affected too please?

https://copr.fedorainfracloud.org/coprs/grillo-delmal/inochi2d/

To check just install through the following commands
```sh
dnf copr enable grillo-delmal/inochi2d
dnf install inochi-session
```

**Comment by EzequielBruni** [comment] 2022-08-15 06:20
@grillo-delmal Okay, I'mma be honest, I forgot about this for a bit. Your build is, sadly, affected.

**Comment by juju2143** [comment] 2022-08-19 20:41
I've got the same error here on Arch Linux, X11, a Nvidia GTX 1650, and the proprietary drivers version 515.65.01. So I guess we probably can rule out Fedora.

**Comment by shincoldfire** [comment] 2022-10-08 18:56
Hi! Is there any progress on this issue? I don't know if this will help, but found some very old forum post with the same error. When the program specified GL version 4.2 it would crash, but when specified older versions or none, the test program worked. See https://community.khronos.org/t/can-not-create-opengl-4-2-context-on-opensuse/66213

**Comment by LunaTheFoxgirl** [comment] 2022-10-08 19:27
The problem is some OpenGL drivers not shipping support for EGL over X11, this is needed to do texture sharing via Pipewire, I enforced it in the current released build but will be reverting that change with the next version.

**Comment by LunaTheFoxgirl** [comment] 2022-10-08 19:28
> I've got the same error here on Arch Linux, X11, a Nvidia GTX 1650, and the proprietary drivers version 515.65.01. So I guess we probably can rule out Fedora.

If you turn drm modesetting on and switch to Wayland on the 515 driver it should work, though NVIDIA's implementation of texture sharing is broken on the 515 driver currently.

**Comment by JigmeDatse** [comment] 2023-01-11 03:02
I'm on Gentoo, and also experiencing this.  I am going to give switching to the nouveau drivers which I *think* Gentoo is recommending anyway.  I *suspect* that if this works out, then it probably is actually a viable solution for many.  The nvidia-drivers have been getting ...  Well not keeping pace with the nouveau drivers.  Which doesn't mean that the nouveau drivers are preferable for everyone, but they appear to be preferable for most people who can get them working.

**Comment by LunaTheFoxgirl** [comment] 2023-04-16 17:13
This should be fixed as of https://github.com/Inochi2D/inochi-session/commit/91984a14d4d3907e0905236931f63cf8df7895dd

**Closed by LunaTheFoxgirl** 2023-04-16 17:13 UTC
Labels: bug
