### ISSUE TITLE
[BUG] Trailing Images when Post-Processing is Enabled

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-session#22] opened 2023-01-16 07:07 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

This is old issue but since it's not listed here yet I thought I'll add the entry. As said in the title, enabling post-processing causes trailing images to appear.

### Reproduction

1, Open Scene Settings
2. Enable Post Processing
3. Move loaded model around.
![Screenshot (542)](https://user-images.githubusercontent.com/7506276/212617845-18a5aacd-c772-45d6-beb7-7b5187e06a15.png)

### System Architecture

x86_64

### Operating System

Windows

### Version

62a328

**Comment by LunaTheFoxgirl** [comment] 2023-01-16 07:16
Which GPU is in use here?

**Comment by helloar14** [comment] 2023-01-16 07:24
GTX 1660 Super, Windows 10, NVIDIA Studio Driver 516.94

**Comment by LunaTheFoxgirl** [comment] 2023-01-16 12:04
Thanks, I will first be able to debug this when I'm back in Denmark since I can't reproduce it here, but will look in to it ASAP.

**Comment by LunaTheFoxgirl** [comment] 2023-05-01 11:42
Fixed by https://github.com/Inochi2D/inochi2d/commit/81ad7db67667e3e87463c4e800f59e5a5ec33267

**Closed by LunaTheFoxgirl** 2023-05-01 11:42 UTC
Labels: Bug
