### ISSUE TITLE
Weird background rendering problems when running on Wayland

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-session#2] opened 2022-07-27 19:12 UTC
When running inochi-session on Wayland if you start moving the window, the model or the opaque things around, they appear to leave a visible trace that doesn't show on screenshots, but also doesn't leave until you refresh the window some way (like minimize + maximize).

Here is a picture that I took on my phone of the issue:
![image](https://user-images.githubusercontent.com/11585030/181349215-28f9afd7-a5b6-4b7b-813c-b2673d7aef4a.png)

This doesn't happen when using X11 or when running on Wayland using the X11 SDL video driver (setting the envs `SDL_VIDEODRIVER=x11 SDL_VIDEO_X11_FORCE_EGL=1`).

This also stopped happening when commenting the line that sets `SDL_HINT_VIDEO_EGL_ALLOW_TRANSPARENCY` to `1` on my debug build.

This was tested on the binary provided by the 0.0.1 AppImage using a compiled cimage.so and on a Fedora 36 environment (SDL2-2.0.22).

**Comment by LunaTheFoxgirl** [comment] 2022-07-27 20:20
My assumption is that the compositor you're using doesn't support transparent framebuffers which are neccesary for xcomposite transparency (to avoid having to use chroma keying)

**Comment by LunaTheFoxgirl** [comment] 2023-04-16 17:10
Closing as duplicate of https://github.com/Inochi2D/inochi-session/issues/22

**Closed by LunaTheFoxgirl** 2023-04-16 17:10 UTC
Labels: bug, duplicate
